'use strict';

import fs from 'fs';
import path from 'path';
import chalk from 'chalk';
import boxen from 'boxen';

// Common patterns that should NEVER go to GitHub
const IGNORE_PATTERNS = {
    node: {
        label: 'Node.js',
        patterns: ['node_modules/', 'npm-debug.log*', '.npm', '.env', '.env.local']
    },
    dotnet: {
        label: '.NET',
        patterns: ['bin/', 'obj/', '*.user', '*.suo', '.vs/', 'packages/']
    },
    general: {
        label: 'General',
        patterns: ['.DS_Store', 'Thumbs.db', '*.log', '.env', '.env.*']
    },
    angular: {
        label: 'Angular',
        patterns: ['dist/', '.angular/', 'node_modules/']
    }
};

async function ignoreCommand() {
    try {
        const gitignorePath = path.join(process.cwd(), '.gitignore');

        // Read existing .gitignore if it exists
        let existing = '';
        if (fs.existsSync(gitignorePath)) {
            existing = fs.readFileSync(gitignorePath, 'utf8');
        }

        // Detect project type
        const hasPackageJson = fs.existsSync(path.join(process.cwd(), 'package.json'));
        const hasCsproj = fs.readdirSync(process.cwd()).some(f => f.endsWith('.csproj'));
        const hasAngularJson = fs.existsSync(path.join(process.cwd(), 'angular.json'));

        // Build patterns to add
        let toAdd = [];
        let detectedProjects = [];

        if (hasPackageJson) {
            detectedProjects.push('Node.js');
            IGNORE_PATTERNS.node.patterns.forEach(p => {
                if (!existing.includes(p)) toAdd.push(p);
            });
        }

        if (hasCsproj) {
            detectedProjects.push('.NET');
            IGNORE_PATTERNS.dotnet.patterns.forEach(p => {
                if (!existing.includes(p)) toAdd.push(p);
            });
        }

        if (hasAngularJson) {
            detectedProjects.push('Angular');
            IGNORE_PATTERNS.angular.patterns.forEach(p => {
                if (!existing.includes(p)) toAdd.push(p);
            });
        }

        // Always add general patterns
        IGNORE_PATTERNS.general.patterns.forEach(p => {
            if (!existing.includes(p)) toAdd.push(p);
        });

        // Remove duplicates
        toAdd = [...new Set(toAdd)];

        if (toAdd.length === 0) {
            console.log(
                boxen(
                    chalk.green('✅ Your .gitignore is already good!\n') +
                    chalk.gray('Nothing new to add.'),
                    { padding: 1, borderColor: 'green', title: '🤖 GitBuddy Ignore', titleAlignment: 'center' }
                )
            );
            return;
        }

        // Write to .gitignore
        const newContent = existing
            ? existing + '\n# Added by GitBuddy\n' + toAdd.join('\n') + '\n'
            : '# Generated by GitBuddy 🤖\n' + toAdd.join('\n') + '\n';

        fs.writeFileSync(gitignorePath, newContent);

        // Build output
        let output = '';

        if (detectedProjects.length > 0) {
            output += chalk.cyan(`🔍 Detected: ${detectedProjects.join(', ')}\n\n`);
        }

        output += chalk.green.bold('✅ Added to .gitignore:\n');
        toAdd.forEach(p => {
            output += chalk.green(`   + ${p}\n`);
        });

        output += chalk.yellow('\n⚠️  These files will now be ignored by Git!\n');
        output += chalk.gray('Run gitbuddy status to see the difference.');

        console.log(
            boxen(output, {
                padding: 1,
                borderColor: 'green',
                title: '🤖 GitBuddy Ignore',
                titleAlignment: 'center'
            })
        );

    } catch (error) {
        console.log(chalk.red('Something went wrong: ' + error.message));
    }
}

export default ignoreCommand;